DeathInfo:
    Show: Yes
    EnableLog: Yes
    DelayTicks: 20
    ShowTicks: 200
    
InventoryProtection:
    Enable: Yes
    EnableItemLog: Yes
    EnableEXPLog: Yes
    ItemRetainPercentage: 50
    ExpRetainPercentage: 50
    DeathGuardSystem:
        Enable: Yes
        EnableLog: Yes
        GuardEntityType: PIG
        KeepDroppedItems: Yes
        KeepLostExp: Yes
        ExpDeletePercentage: 20
        ProtectSeconds: 900
        Attack:
            Enable: Yes
            DamageToSecondFactor: 1
            Notify: Yes
            NotifySecondsInterval: 10
            HitBack:
                Enable: Yes
                TolerateHits: 2
                LightningEffect: Yes
                SecondsInterval: 5
                Damage: 4
                SetAttackerOnFire: Yes
                FireTicks: 100
            CanAttack:
                Enemy: Yes
                Neutral: Yes
                Wilderness: No
        Bless:
            Enable: Yes
            EachBlessSecondMax: 60
            EachSecondCostExp: 0.6
            Notify: Yes
            CanBless:
                SameFaction: Yes
                Ally: Yes
                Truce: Yes
                Wilderness: No

Translation:
    world: "Main world"
    
System:
    FactionsSupport: No
    # mushroom-growth deny = area disable InventoryProtection
    WorldGuardSupport: No
    # Change this to get you and this plugin eaten by Ender Dragon, not really, seriously.
    PluginVersion: ${version}