name: ${name}
artifactId: ${artifactId}
version: ${version}
description: ${description}
author: ${author}
website: ${url}
 
main: ${groupId}.${artifactId}.${mainClass}
mainCommand: ${mainCommand}
depend: [Citizens]
softdepend: [mcore, Factions]

commands:
    ${mainCommand}:
        description: Basic command.
        usage: Type /<command> help to get help.
        permission: ${artifactId}.use
        permission-message: You are not permitted to use this plugin.

permissions:
    ${artifactId}.*:
        description: Gives access to all ${name} commands.
        default: op
    ${artifactId}.admin:
        description: Gives access to all ${name} administrative commands.
        children:
            ${artifactId}.reload: true
        default: op
    ${artifactId}.reload:
        description: Reloads the plugin.
        default: op
    ${artifactId}.use:
        description: Gives access to use this plugin.
        default: true
    ${artifactId}.basic:
        description: Gives access to use most of the function of this plugin.
        children:
            ${artifactId}.canHaveDeathItemProtection: true
            ${artifactId}.canHaveGuard: true
            ${artifactId}.canAttackGuard: true
            ${artifactId}.canBlessGuard: true
            ${artifactId}.canHaveDeathInfo: true
        default: true
    ${artifactId}.canHaveDeathItemProtection:
        description: Allows player to have death item protection.
        default: true
    ${artifactId}.canHaveGuard:
        description: Allows player to have death guard.
        default: true
    ${artifactId}.canAttackGuard:
        description: Allows player to attack death guard.
        default: true
    ${artifactId}.canBlessGuard:
        description: Allows player to bless death guard.
        default: true
    ${artifactId}.canHaveDeathInfo:
        description: Allows player to have death info display.
        default: true